nylas/nylas-ruby

README.md, lib/namespace.rb, spec/deltas_spec.rb
Both were just missing slashes in their URLs.
Didn't notice https://github.com/inboxapp/inbox-ruby/pull/16 until just opening this. I'll amend my commit once that is in.
Also (although this is out of the scope of this pull request), thoughts on somehow returning the last cursor/signaling that the account has no more deltas? There's currently no way to know what the best cursor is to use for next time `deltas` is invoked.
=> Fix namespace get_cursor/deltas methods

Gemfile, README.md, inbox.gemspec, lib/inbox.rb, lib/namespace.rb, spec/deltas_spec.rb, spec/fixtures/delta_stream.txt
As proposed in #21 :
My implementation adds two new dependencies - yajl-ruby for parsing JSON streams and em-http-request for streaming via HTTP.
Requesting feedback on the following:
I have not handled any HTTP errors in delta_stream because I am not entirely sure which errors the /delta/streaming endpoint can throw.
I have not implemented any sort of recovery if the connection fails. Not sure if this should be a part of the delta_stream function or not.
I am welcome to other feedback and proposals for alternate methods. I have also tried implementing this with yajl-ruby's HttpStream class, but it does not support HTTPS.
=> Add support for delta streaming API to Namespace

spec/deltas_spec.rb, spec/file_spec.rb, spec/message_spec.rb
* Namespaces have been removed. This errant `require` will blow up.
* Fix RSpec warnings for raise_error
=> Fix failing specs

.rspec, spec/account_api_spec.rb, spec/account_spec.rb, spec/deltas_spec.rb, spec/draft_spec.rb, spec/event_spec.rb, spec/file_spec.rb, spec/inbox_spec.rb, spec/message_spec.rb, spec/opensource_spec.rb, spec/restful_model_collection_spec.rb, spec/restful_model_spec.rb, spec/spec_helper.rb, spec/thread_spec.rb
* Remove explicit LOAD_PATH mutation
* Require `spec_helper` via .rspec command line arg
* Set RACK_ENV to test in the spec_helper
* Remove extraneous requires for webmock/rspec
NOTE: The specs still won't pass until #36 is merged. This PR builds upon the work done there.
=> Standardize RSpec configuration

README.md
* `#each` without a block returns an `Enumerator`, which can be used like an `Enumerable`. Also, `#select`-ing on a collection of messages will still return a subset of messages. We then map again over that to collect the list of files, which we can download.
* In Ruby, a symbol (e.g., `:files?`) can be converted to a `Proc` by prepending an ampersand (e.g., `&:files #=> :files?.to_proc`). This can be used with methods like `Enumerable#select` and `Enumerable#map` which take a `Proc`/block to filter the enumerable.
* Fix broken code fence blocks.
* Normalize README formatting.
=> Fix Enuerator documentation and README formatting

lib/inbox.rb
This makes it possible to capture ANY Error raised by Nylas via:
```ruby
def foo
rescue Inbox::Error => e
end
```
rather than needing to know all possible errors which could be raised by Nylas.
=> Use base Inbox::Error for all errors

lib/api_account.rb, spec/account_api_spec.rb, spec/fixtures/account_api.txt
The `/account` API exposes the current `sync_state`, but we were not pulling that across in the `APIAccount` object. Now we do!
=> Expose sync_state on APIAccount

spec/deltas_spec.rb
A recent change (052e9146d0ee04d9a5b348c310a4a00e676c69fe) added `exclude_folders=false` to requests on the Delta API, but the specs were not updated to account for the change. This fixes that.
=> Fix specs broken by addition of `exclude_folders`

lib/inbox.rb, spec/deltas_spec.rb
This behavior is consistent with other APIs which act on a collection.
I also refactored the Delta API specs to user RSpec features and organizational patterns.
=> Return Enumerator from `#deltas` API when no block is given.

CHANGELOG.md, README.md, lib/inbox.rb, spec/deltas_spec.rb
`delta_stream` is a blocking call, and previously had no good way to run
in parallel in order to stream several accounts at once.
EventMachine's run loop was removed from the library so that SDK
implementers can create multiple streams inside their own EventMachine
run block.
`delta_stream` must be wrapped in an `EventMachine.run` block in order
to function, whereas before it could be called plain. Two tests have
been refactored to reflect this, and documentation has been updated.
=> Refactor `delta_stream` to allow multiple streams

lib/restful_model_collection.rb, spec/fixtures/messages_reply_100.txt, spec/fixtures/messages_reply_2.txt, spec/restful_model_collection_spec.rb
The limit and offset filters, which were set correctly in the `where`
function, were being overriden in the `get_model_collection` function
by the offset and limit parameters passed to it (with defaults). The
function now checks if limit or offset are already present in the list
of filters before applying its own.
Also includes new tests of the `where` function.
Close issue #66.
=> Allow limit and offset filters for collections

README.md, lib/api_thread.rb, lib/expanded_message.rb, lib/message.rb, lib/nylas.rb, spec/expanded_message_spec.rb, spec/nylas_spec.rb, spec/thread_spec.rb
Sometimes you need to get collection of expanded messages and it's not efficient to do
```ruby
api.messages.each do |message|
expanded_message = message.expanded
puts expanded_message.message_id
end
```
because it produces an additional query to the Nylas API for each `expanded` method call.
This PR adds ability to request the collection of expanded messages, like
```ruby
api.messages(expanded: true).each do |expanded_message|
puts expanded_message.message_id
end
```
or 
```ruby
thread.messages(expanded: true).each do |expanded_message|
puts expanded_message.message_id
end
```
It also allows getting single expanded message in one API call with
```ruby
expanded_message = api.messages(expanded: true).find(id)
```
which is more efficient than getting it with two queries
```ruby
message = …
```
=> Add ability to get collection of expanded messages

lib/restful_model_collection.rb, spec/restful_model_collection_spec.rb
I want to meditate on preserving the "evaluate each page as it's loaded" behavior overnight. Will take another stab at it in the morning
Resolves #66
=> Each and range no longer break limit filters

CONTRIBUTING.md, gemfiles/Gemfile.rails4.lock, gemfiles/Gemfile.rails5.lock, gemfiles/Gemfile.rest-client.1.lock, gemfiles/Gemfile.rest-client.2.lock
When we upgrade the version, our cross-compatible gemfiles will need to have their lockfile update as well.
Otherwise CI will get nervous because we're trying to load a new version of the gem that isn't specified in the lockfile.
=> Update lockfiles after changing the version

tests/system.rb
When I was running the feature tests, I got some surprising behavior where it would move forward two steps instead of one.
This is because it wasn't waiting for me to hit the return key to validate my input, so when I hit "Y" + Enter it moved twice instead of once.
I've changed to use `gets` instead, so that future contributors don't run into the same behavior.
=> Remove surprising behavior of not requiring enter on user input

lib/nylas.rb, lib/nylas/account.rb, lib/nylas/draft.rb, lib/nylas/event.rb, lib/nylas/file.rb, lib/nylas/message.rb, lib/nylas/restful_model.rb, lib/nylas/restful_model_collection.rb, spec/inbox_spec.rb, spec/nylas_spec.rb
In our project we use `RestClient` not only for Nylas so we get our http headers corrupted with Nylas stuff :(
=> Remove global RestClient hooks.

lib/nylas.rb, lib/nylas/to_query.rb
For some reason, we had a require for `active_support` in lib/nylas,
which meant that even though we didn't declare a dependency on
ActiveSupport, we assumed that you would be using it.
This removes that in favor of a small class that casts hashes to query
strings.
We may be able to get rid of this if we leverage RestClient for
URL building.
=> Remove implicit dependency on ActiveSupport

lib/nylas/message.rb, spec/message_spec.rb
This resolves https://github.com/nylas/nylas-ruby/issues/57 by making the interface more explicit about the types it expects.
I generally prefer to do this on setting the data as opposed to on parsing, what do you think @khamidou? An example of doing the casting/validation on input is here: https://github.com/nylas/nylas-ruby/pull/133
=> Make type errors for message folders and labels explicit

lib/nylas/message.rb, spec/message_spec.rb, tests/system.rb
Resolves https://github.com/nylas/nylas-ruby/issues/118
I chose to not overwrite the existing `date` method as that could result in surprises for our consumers. Instead, I went with overwriting the `date=` so that it coerces the date to a string when it's set with a real date object, and then it parses it back out as `parsed_date` for convenience.
I'll need to update this when we merge #113
=> Expose date fields as ruby dates

.overcommit.yml
This extends #161 a bit so that you don't have to `bundle exec git commit` if you have multiple versions of rubocop installed.
=> Use the bundled version of rubocop instead of system version

lib/nylas/model.rb, lib/nylas/model/attributable.rb, spec/nylas/model_spec.rb
When finding a particular record after the API had new fields added to
it, exceptions would be raised as the model would reload itself and
attempt to set a field that doesn't exist.
By making reload use the same logic as instantiation, we're able to
avoid exceptions being raised on find when new fields are added to the
API
This covers an additional use case from https://github.com/nylas/nylas-ruby/pull/186, which slipped past me.
This also resolves #188
=> Finding a model works when new fields are added to the API

lib/nylas/message.rb, spec/nylas/message_spec.rb
When message fetched using `find`, it is always not expanded. Allow to use `expanded` method of message to return expanded version always.
If headers nil, just re-fetch expanded view of message.
It allows to run following:
```
message = api.messages.find(id)
message.expanded.headers.in_reply_to
```
Fix issue https://github.com/nylas/nylas-ruby/issues/189
=> Add expanded method to message

lib/nylas/draft.rb, lib/nylas/message.rb
It looks like mistype, but i think, for folder attribute type should be `folder`
PR fix it for message and draft models
=> Fix wrong type for folder attribute in message, draft

lib/nylas/constraints.rb, spec/nylas/collection_spec.rb
Count request with `where` constraints is not working. Method `Nylas::Constraints#merge` erases `where` from parent constraints. It merges `where` from args to themselves.
=> fix count with `where` api request

.travis.yml, CHANGELOG.md, gem_config.rb
According to [the Ruby maintainence page](https://www.ruby-lang.org/en/downloads/branches/), Ruby 2.2 reached end-of-life on 2018-03-31, and Ruby 2.3 reaches end-of-life on 2019-03-31, less than a month from today. We should drop support for both of them.
However, we can add support for Ruby 2.5 and 2.6, which are both in normal maintenance.
=> Drop support for Ruby 2.2 and 2.3 (EOL)

CHANGELOG.md, README.md, gem_config.rb, lib/nylas/api.rb, lib/nylas/native_authentication.rb, spec/nylas/native_authentication_spec.rb, spec/spec_helper.rb
Add `scopes` argument to `Nylas::API#authenticate` for [selective sync](https://docs.nylas.com/docs/how-to-use-selective-sync).
Python SDK: https://github.com/nylas/nylas-python/pull/106
=> Add scopes arg for native authentication

README.md
Update scopes section of readme to reference granular scopes and point to new authentication document instead of selective sync.
=> update readme with granular scopes

lib/nylas/file.rb
When downloading file exception raised:
`Encoding::UndefinedConversionError: "\x84" from ASCII-8BIT to UTF-8`
It fix following code to run:
```
message = api.messages.find(id)
content = message.files[0].download
```
=> Fix encoding issue when download attachments

lib/nylas/draft.rb, lib/nylas/message.rb, lib/nylas/model.rb, lib/nylas/model/transferable.rb, lib/nylas/thread.rb, spec/nylas/draft_spec.rb, spec/nylas/message_spec.rb, spec/nylas/thread_spec.rb
When some model object initialized, also initialized and included dependent model objects.
For example when **message** is initialized, also will be initialized:  **events**, **files**, **folder** and **labels**. But this objects api will be nil, and it is not possible and easy to start using execute api methods.
Example:
```
message = api.messages.find(id)
content = message.files[0].download
```
Download will fail, api is not initialized for file.
This PR add `Transferable` class extension, using it it is possible to specify transfer of attributes to dependent objects using following notation:
```
module Nylas
class Message
...
transfer :api, to: %i[events files folder labels]
end
end
```
Transfer api added to message, draft, thread. It is rspec covered.
=> Transfer api attribute to included objects

lib/nylas.rb, lib/nylas/event.rb, lib/nylas/when.rb
This PR adds support for `when` in `Nylas::Event` for types other than `timespan`. I did this in the quickest/most obvious way to me - if there's a better way to implement this, I'll be happy to make any changes.
This is related to #199 and may fix that issue.
=> Add Nylas::When for generic time object handling

lib/nylas.rb, lib/nylas/filter_attributes.rb, lib/nylas/message.rb, spec/nylas/filter_attributes_spec.rb, spec/nylas/message_spec.rb
Right now there is no way to set a `label` on a `message`.
API accepts `label_ids` as an array of string of label ids.
This PR also add `UPDATABLE_ATTRIBUTES` to just allow few attributes to
be updated allowed by API instead of having all attributes to be
updated.
=> Allow setting `label_ids` on a message

.travis.yml, gemfiles/Gemfile.rails6
As Rails 6.0 is released we can should also add that to CI.
As Rails 6 only supports ruby 2.5 and above we need to 
add custom matrix for that in CI.
- Gemfile.rails6 added.
- >travis.yml update to run tests with Rails 6.
=> Test against Rails 6 version

lib/nylas/message.rb, lib/nylas/model.rb, spec/nylas/message_spec.rb
Right now when we call `.save` on a message it raises an error 
because `labels` attributes also being sent to server along with 
other attributes. Server won't know anything about `labels` so it
was failing. This issues also mentioned here https://github.com/nylas/nylas-ruby/issues/183
This PR right now rejecting the `labels` attribute to be sent to server so 
we can save a `message`. 
In this PR also using a feature where we can define `exclude_when` call 
for certain actions.
=> Fix an error occurring on `message.save`

lib/nylas/contact.rb
We are not using a single webpage anywhere so we can remove this from the attribute list
=> Remove unused attribute `web_page` from contact

lib/nylas/calendar.rb
This PR adds support for new attributes that were recently added to the Nylas calendar API: `is_primary`, `location` and `timezone`. To match the convention established by the `read_only?` method, it also adds a `primary?` method which simply returns the value of `is_primary`.
=> Add is_primary and other new Calendar attributes

lib/nylas/model/attributable.rb, lib/nylas/model/attributes.rb
A couple of problems came up in our production app when Nylas added new attributes to API objects. One was a constant barrage of Rails logger warnings upon each request that drowned out other log traffic. A second more serious issue was that upon certain operations, the gem would raise exceptions about the unexpected attributes, causing failures in our code even though the requests were successful.
The [Nylas API docs](https://docs.nylas.com/reference#api-versioning) state:
> Nylas considers additive changes to be non-breaking. This means we may add additional fields to an API response object without releasing a new API version, so your application should handle this possibility.
I believe these changes to the gem are necessary in order to respect this very reasonable policy.
I confirm …
=> Handle new attributes added to API gracefully

lib/nylas/physical_address.rb
Adding this new field to address the changes for https://app.clubhouse.io/nylas/story/22758/missing-street-address-line-2-data-from-google-contacts-even-though-it-shows-in-the-gdata
=> Adding secondary_address field to physical address model

lib/nylas/http_client.rb, nylas.gemspec, spec/nylas/http_client_spec.rb, spec/nylas/message_spec.rb
In `http_client.rb` when parsing the response from an API call, if `JSON.parse` raises an error, the error is rescued and the raw response returned.  This causes an error downstream in `attributable.rb` and returns a non-specific error `wrong number of arguments (given 1, expected 0)`.
The one instance of a consistently reproducible parse error I was able to find using the Nylas API was an email with the unicode character `\ud83d`, thus is was used as the primary test case.  Technically speaking, `\ud83d` is not valid, but IMO, instead of raising an error, replacing the offending character or returning the string literal value is a better approach.
1. Given an error when parsing JSON, no longer rescue the error.
2. Replace JSON with Yajl for parsing responses (also used in the Nylas …
=> Fix JSON parsing behavior

lib/nylas/message.rb, spec/nylas/message_spec.rb
When updating a message in Outlook, we throw an error if the folder sub-object is present in the request.
```
/Users/nickbair/.rvm/gems/ruby-2.6.5/gems/nylas-4.6.2/lib/nylas/http_client.rb:166:in `handle_anticipated_failure_mode': Invalid id: {u'display_name': u'Junk Email', u'id': u'a8cquo7scqx8qpzd5hslmbeqz', u'name': u'spam'} (Nylas::InvalidRequest)
```
If a folder is present when updating a message, store the folder's `id` in `folder_id` and remove `folder` from the request payload that is sent to the Nylas API.
=> Remove folder on message.save for updates

lib/nylas/file.rb
This ensures the filename will be compatible with rb_sysopen. See the [Clubhouse story](https://app.clubhouse.io/nylas/story/49502) for more details.
=> Truncate the returned filename so it's less than 256 characters

lib/nylas/draft.rb, spec/nylas/draft_spec.rb
Add support for message tracking to the drafts class.  Users who are not adding the tracking attribute to their draft will not hit the new code.
=> Add message tracking to drafts.

lib/nylas/new_message.rb, spec/nylas/new_message_spec.rb
The new message class (used for sending directly) in the SDK is missing the `reply_to` attribute (https://docs.nylas.com/reference#sending-directly).  Added this attribute and a test for the class.
=> Add reply_to to NewMessage

lib/nylas/file.rb
Adds `content_disposition` attribute to files.  Content disposition is included by the API when fetching messages with attachments:
```
{
...
"files":
[{"content_disposition": "attachment", ...}]
}
```
=> Add content_disposition to file attrs.

lib/nylas.rb
HTTP::CookieJar uses unsafe class caching for dynamically loading cookie jar implementations. If 2 rest-client instances are instantiated at the same time, (for instance if you spawn 2 threads), then non-deterministic behaviour can occur whereby the Hash cookie jar isn't entirely loaded and cached. This _sometimes_ [raises an exception](https://github.com/sparklemotion/http-cookie/blob/master/lib/http/cookie_jar/abstract_store.rb#L21) because the Hash CookieJar can't be found (it's a race condition)
See:
- https://github.com/sparklemotion/http-cookie/issues/27
- https://github.com/sparklemotion/http-cookie/issues/6
Forcing an instantiation of the jar onload will force the Hash CookieJar to load before the system has a chance to spawn any threads.
Note this should technically be fixed in …
=> Fix thread-safety issue in HTTP::CookieJar loading

lib/nylas/account.rb, spec/nylas/account_spec.rb
We are getting `provider` attribute when fetching account details
and it's good to have it available to read via SDK.
This PR adds `provider` attribute to `Nylas::Account` so it
can be populated when fetched via API.
This was also requested in #256
Changes:
- Update `Nylas::Account` to add `provider` attribute.
=> Add provider attribute to Account model

CHANGELOG.md, lib/nylas/collection.rb, spec/nylas/collection_spec.rb, spec/spec_helper.rb
This PR fixes issue where downloading a file for the
message which is fetched via `find_model` method.
This PR updates `find_model` to fetch from API and then use
`from_hash` to initialize object instead of just using `reload`
which was internally using `assign` method to assign values.
By doing this way `file` object properly gets `api` attribute
assigned and `download` method works.
This issue was reported in #258
Changes:
- Update `Nylas::Collection` to update `find_model` method
to fetch again fron API and use `from_hash` method.
=> Fix issue where download a file fetch via `find`

lib/nylas/collection.rb, lib/nylas/deltas_collection.rb
We have done some changes in #283 to make this gem works with
Ruby 3 and above but there are few changes left which are covered
in this PR. This PR fixes fetching `deltas` and fixes fetching an
object when content-type is not `json`.
This PR has been verified based on feedback received in #289
More details about this upgrade can be read here:
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
=> Remaining fixes required to work with Ruby3

lib/nylas/event.rb, spec/nylas/event_spec.rb
We have identified that few of the event update calls to the API
sends `object` and `account_id` attributes and it should not be
allowed to send.
This PR stops sending `id`, `object` and `account_id` attribute
to the API when we call `.save` on an event object. These are
readonly object on server and we should avoid sending it.
=> Exclude `id`, `object` and `account_id` when updating an event

CHANGELOG.md, lib/nylas/api.rb, spec/nylas/api_spec.rb
This PR adds `authentication_url` method to generate a URL to redirect
to login through Nylas hosted authentication flow.
Mode information can be found here about how authentication flow works
https://docs.nylas.com/reference#oauth
These changes also requested in #223 and also worked on a bit in #227
Changes:
- Update `Nylas::API` to add `authentication_url` method.
=> Add support for authentication_url for hosted authentication

.rubocop.yml, lib/nylas/collection.rb, spec/nylas/collection_spec.rb
Currently sending `view` in the query param is not supported when
fetching a single record and we want to support it as it's already
supported in API. This PR allows to chain `view` related methods before
`find` so that `view` is send to API.
This PR fixes #189 where it has been requested that expanded message
should be fetched in single call by sending `view=expanded` in query param.
Changes:
- Update `Nylas::Collection` to send `view` in query params when a view
related method is chained.
=> Support for `messages.expanded.find(id)` to get expanded message

lib/nylas/raw_message.rb, spec/nylas/raw_message_spec.rb
We added support for sending raw mime type message in #169
and it stopped working after an upgrade. This PR fixes that.
This PR also fixes #122
Changes:
- Fix `Nylas::RawMessage#send!` to send raw mime type.
=> Fixed issue when sending message raw mime type

CHANGELOG.md, lib/nylas/http_client.rb, spec/nylas/http_client_spec.rb
Based on versioning docs https://developer.nylas.com/docs/developer-tools/api/versioning/
we should be sending `Nylas-API-Version` header with supprted version
number to the API. This PR impements it and also set it to 2.2 which is
latest version of API
Changes:
- Update `Nylas::HttpClient` to send `Nylas-API-Version` header.
=> Add `Nylas-API-Version` header to be sent to API

lib/nylas/delta.rb, lib/nylas/deltas.rb, spec/nylas/delta_spec.rb, spec/nylas/deltas_spec.rb
Background:
Currently `Delta` object for changes like `Message` and `Event`
having `account_id` as nil and it was also reported in #266.
This PR fixes the issue where the delta object properly assigning
`account_id` and other attributes to the attached model object
for messages and others.
Changes:
- Update `Delta` class to handle case where changes are inside
`attributes` key. Also marked `object_attributes_with_ids` as
private.
- Update `Deltas` class to have `.last` method which useful when
having multiple objects.
=> Fix attributes assignment for `Delta`

lib/nylas/contact.rb, lib/nylas/draft.rb, lib/nylas/event.rb, lib/nylas/message.rb, lib/nylas/model.rb, lib/nylas/model/attributable.rb, lib/nylas/model/attribute_definition.rb, lib/nylas/model/attributes.rb, lib/nylas/model/list_attribute_definition.rb, lib/nylas/rsvp.rb, lib/nylas/when.rb, spec/nylas/event_spec.rb, spec/nylas/model/attributes_spec.rb, spec/spec_helper.rb
Background:
Currently in API there are few attributes which should be treated as
read only and we should not send them to API when creating and updating.
We did a solution in #291 but it's not working for the cases where
attributes are nested. This change also suggested in #120.
This PR allows us setting up read only attibute on attribute level
and they will not be sent to the API when creating and updating.
Changes:
- Removed usage of `exclude_when` and using `read_only` to determine
if attribute is read_only or not.
- Added `serialize_for_api` method in `Nylas::Model::Attributes` to
be used for create and update calls.
=> Support for read only attributes

CHANGELOG.md, examples/plain-ruby/events.rb, lib/nylas/event.rb, lib/nylas/http_client.rb, spec/nylas/event_spec.rb, spec/nylas/http_client_spec.rb
The Nylas Calendar API has a new beta feature of adding a new [metadata field to calendar events](https://www.nylas.com/blog/event-metadata). This PR makes the feature available via the Nylas Ruby SDK. 
To create a new event with event metadata, you can create a `Hash` object with a mapping of key-value pairs for the metadata:
```
api.events.create(
title: "A fun event!",
...
metadata: {
event_type: "gathering"
}
).to_h
```
To query events based on metadata, you can filter on three different parameters:
- `metadata_key` (string or array) to filter based on the keys within the metadata object
- `metadata_value` (string or array) to filter based on the value within the metadata object
- `metadata_pair` (hash) to filter based on the key-value pairs within the metadata object
These filters …
=> [58503] Ruby SDK support for metadata for Events

lib/nylas/http_client.rb, spec/nylas/collection_spec.rb, spec/nylas/http_client_spec.rb, spec/spec_helper.rb
Background:
Currently if server returns any error where content-type is not a JSON
is not raising error in `Nylas` namespace and returns
`RestClient::Response` instead. This issue is also raised in #274
and #272. It has been found that it breaks after #268 where we 
have fixed parsing error if content type is not json.
This PR makes sure that whatever content-type is returned from
API in error response it always raises error in `Nylas`
namespace.
Changes:
- Update `Nylas::HttpClient` to parse error response beforing
raising exception.
=> Fix exception raise when content-type is not JSON

.gitignore, CHANGELOG.md, lib/nylas/draft.rb, spec/nylas/draft_spec.rb
When attaching a file, the user would pass in the `File` object after a successful upload, however without extracting the `file_ids` the draft would be created without attachments
=> Fix issue where files couldn't be attached to drafts

CHANGELOG.md, lib/nylas/draft.rb, lib/nylas/model.rb, spec/nylas/draft_spec.rb, spec/nylas/thread_spec.rb
When making updates to the draft object on the server side (via `.update`) the version number is incremented upon successful update. However, the local object does not update the value when it's returned from the server. This causes an issue when, the user attempts to re-update the draft a second time and the version number has not been incremented. Now, when calling `.update` the version is updated with the value returned from the payload.
=> [61539] Draft version not updating after `update`

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.1.0 release bringing in the following new features:
* Add support for read only attributes (#298)
* Add `save_all_attributes` and `update_all_attributes` methods to support nullifying attributes. (#299)
* Add support new `Event` metadata feature (#300)
* Fix attributes assignment for `Delta` (#297)  
* Fix issue where files couldn't be attached to drafts (#302)
* Fix exception raise when content-type is not JSON (#303)
* Fix issue where draft version wouldn't update after `update` or `save` (#304)
=> [61552] 5.1.0 Release

CHANGELOG.md, examples/plain-ruby/room_resource.rb, lib/nylas.rb, lib/nylas/api.rb, lib/nylas/room_resource.rb, spec/nylas/room_resource_spec.rb
This adds support for the `/resource` endpoint and the Nylas `Room Resource` object. More information can be found [in the docs](https://developer.nylas.com/docs/api/#tag--Room-Resources).
Currently, the `/resource` endpoint only supports the `GET` operation without any extra functionality like filtering. To get a list of all room resource objects attached to your account,  you can do the following:
```
#!/usr/bin/env ruby
require 'nylas'
app_id: CLIENT_ID,
app_secret: CLIENT_SECRET,
access_token: ACCESS_TOKEN
)
resources = nylas.room_resources
```
=> [61632] Add `Room Resource` support

CHANGELOG.md, lib/nylas/http_client.rb, spec/nylas/http_client_spec.rb
**Issue**
API response from nylas GET `/oauth/authorize` returns HTTP=302 with empty body that causes call raise of exception (due it is not 200 code), but fails to do it due the empty body.
**Solution**
I have added list of successful HTTP codes (add more if your API responds with another non-error codes) to the check in `#handle_anticipated_failure_mode` method.
=> added list of successful http codes

lib/nylas/api.rb, lib/nylas/http_client.rb
During working with Ireland region we found out that we need to use Ireland API server URL in `api_server` argument for API client instantiation. 
Additionally to this parameter, we met `service_domain` argument which seems to be not used anymore. 
The last usage of this parameter was found at https://rdoc.info/gems/inbox/1.3.0/Inbox%2FAPI:url_for_authentication - in order to avoid any further confusion this PR is intended to remove unused argument.
=> cleanup: unused service_domain removed

CHANGELOG.md, lib/nylas/message.rb, spec/nylas/message_spec.rb
When calling `message.expanded`, the attributes of the message that have an `api` value (such as `files`) do not retain the API value after the object's values were updated. The reason for this is that the `transfer_attributes` method is never called, thus the message object never passes the `api` value to the newly parsed data. Now we manually invoke the method call to ensure all of the attributes that need an `api` value get initialized with it.
=> [63670] Fix `api` value resetting after `message.expanded` call

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.2.0 release bringing in the following new features:
* Add support for `Room Resource` (#307)
* Fix issue where "302 Redirect" response codes were treated as errors (#306)
* Fix issue where `api` value was overridden when calling `message.expanded` (#311, issue: #308)
=> [64108] 5.2.0 Release

CHANGELOG.md, lib/nylas/delta.rb, spec/nylas/delta_spec.rb, spec/nylas/deltas_spec.rb
Fixes Bug #314 
`/deltas` endpoint has the option to respond to the _expanded_ option however, the object `Nylas::Delta` doesn't have the `#headers` attribute; Field responsible for the _expanded_ information.
This commit aims to add the `#headers` attribute to be filled with the _expanded_ response when available.
=> Add `#headers` to `Nylas::Delta`

CHANGELOG.md, lib/nylas/http_client.rb
In the rare case, the API server might return a server error but with a HTML body instead of a JSON type. This causes the parser to throw a parse error, but it does not return that the server ran into an error. Now, if parsing fails we also check if we encountered an error and if we did, we should propagate the error back to the user for better information. 
=> [64639] Return API error regardless if response is JSON

CHANGELOG.md, lib/nylas/new_message.rb
The double splat operator was missing causing a ArgumentError when calling `Nylas::API#send!`
=> [63799] Fix ArgumentError when sending email

CHANGELOG.md, lib/nylas/thread.rb, spec/nylas/thread_spec.rb
This will help deserialize messages for GET requests sent to /threads/{{id}}?view=expanded.
Issue is that when tries to get thread with view=expanded, it doesn't deserialize messages.
=> Add messages attribute to Thread.

.rubocop.yml, CHANGELOG.md, examples/plain-ruby/neural.rb, lib/nylas.rb, lib/nylas/api.rb, lib/nylas/categorize.rb, lib/nylas/http_client.rb, lib/nylas/model/attributable.rb, lib/nylas/neural.rb, lib/nylas/neural_categorizer.rb, lib/nylas/neural_clean_conversation.rb, lib/nylas/neural_contact_link.rb, lib/nylas/neural_contact_name.rb, lib/nylas/neural_message_options.rb, lib/nylas/neural_ocr.rb, lib/nylas/neural_sentiment_analysis.rb, lib/nylas/neural_signature_contact.rb, lib/nylas/neural_signature_extraction.rb, lib/nylas/types.rb, spec/nylas/neural_spec.rb
This PR brings support for the Nylas [Neural API](https://developer.nylas.com/docs/intelligence/). The Neural API exposes endpoints that perform intelligent analysis on items in your Nylas account. This change will enable users to access the features of the Nylas Neural API and provides some utility functions to help improve the user's workflow.
To use [Sentiment Analysis](https://developer.nylas.com/docs/intelligence/sentiment-analysis/):
```ruby
message_analysis = nylas.neural.sentiment_analysis_message([MESSAGE_ID])
text_analysis = nylas.neural.sentiment_analysis_text("Hi, thank you so much for reaching out! We can catch up tomorrow.")
```
To use [Signature Extraction](https://developer.nylas.com/docs/intelligence/signature-extraction/):
```ruby
const signature = …
```
=> [63813] Neural API Support

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.3.0 release bringing in the following new features:
* Add support for the Neural API (#318)
* Fix issue where `Delta` did not have a header attribute for expanded headers (#315, #314)
* Fix ArgumentError when calling `Nylas::API#send!` due to missing double splat (**) (#317, #310)
* Fix issue where server errors are not reported if HTML is returned (#316, #313)
* Fix issue where expanded `Thread` objects were not returning messages (#319, #321)
=> v5.3.0 Release

CHANGELOG.md, lib/nylas/draft.rb, spec/nylas/draft_spec.rb
The following is the code snippet is found on our Nylas docs for Ruby PUT `/drafts/{id}`: https://developer.nylas.com/docs/api/#put/drafts/id
```ruby
draft_to_change = api.drafts.find("51si***")
draft_to_change.update(display_name: "My Renamed Draft")
```
However in practice this fails. The reason is because the API expects a version number to be passed in with a PUT call. In the Ruby SDK we only pass the updated parameters to the API, so if the user doesn't explicitly send in the `version` number, the SDK doesn't do it for them and triggers the error. To adhere to the documentation and the API's expectation, we should send the version number in the payload if the user never adds it in explicitly.
I confirm that this contribution is made under the terms of the MIT license and that I have …
=> [67394] Fix updating `Draft` failing if no version number provided

examples/plain-ruby/drafts.rb
Move "Creating a draft" to the top so that subsequent steps (e.g. Retrieving a particular draft) will still work even if a user has no pre-existing drafts
=> Change drafts example so that it works even when a user has no existing drafts

CHANGELOG.md, lib/nylas/draft.rb, spec/nylas/draft_spec.rb
We shouldn't be updating a draft every time the user tries to to send a draft. This causes an unnecessary PUT call, and potentially causes a delay in the syncing process for the end user. So now, calling `.send` on a draft will not trigger an update/PUT call. Also to make up for this change, if a user wants to send a draft that they haven't saved (have not triggered a POST `/drafts` call), the SDK will send the full body in the POST call to `/send` allowing the user to send a message directly without having to create and save a draft object first.
=> [68888] Modify Draft Sending logic

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.4.0 release bringing in the following new features:
* Add support for Event Conferencing (#320)
* Fix update draft failing if version is not explicitly set (#324)
* Fix draft `.send` logic (#323)
=> v5.4.0 Release

lib/nylas/draft.rb, spec/nylas/draft_spec.rb
This fixes a bug where if tracking information is enabled on a draft it sends directly rather than sending the existing draft. If a draft has already been saved this means the actual draft message never gets sent and a new message is created. The message should instead only be sent directly if it hasn't been saved and otherwise conditionally add the tracking information to the draft message.
I've also updated the draft spec to reflect this change. Previously it was expecting:
`{\"id\":\"draft-1234\",\"version\":5,\"tracking\":{\"links\":true,\"opens\":true,\"thread_replies\":true,\"payload\":\"this is a payload\"}}`
It should instead expect `draft_id` rather than `id`:
`{\"draft_id\":\"draft-1234\",\"version\":5,\"tracking\":{\"links\":true,\"opens\":true,\"thread_replies\":true,\"payload\ …
=> Update draft send method to send existing draft when tracking is enabled

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.4.1 release fixes the following:
- Fix draft send method to send existing draft when tracking is enabled (#327)
=> v5.4.1 Release

CHANGELOG.md, examples/plain-ruby/events.rb, lib/nylas.rb, lib/nylas/event.rb, lib/nylas/event_notification.rb, spec/nylas/event_spec.rb
Add support for [Event notifications](https://developer.nylas.com/docs/connectivity/calendar/event-notifications).
To add notifications to an event:
```ruby
api.events.create(
title: "A fun event!",
location: "The Party Zone",
calendar_id: {CALENDAR_ID},
conferencing: {
provider: "Zoom Meeting",
details: {
url: "https://us02web.zoom.us/j/****************",
meeting_code: "213",
password: "xyz",
phone: ["+11234567890"]
},
notifications: [
{
body: "Reminding you about our meeting.",
minutes_before_event: 600,
subject: "Test Event Notification",
type: "email"
},
{
type: "webhook",
minutes_before_event: 600,
url: "https://hooks.service.com/services/T01A03EEXDE/B01TBNH532R/HubIZu1zog4oYdFqQ8VUcuiW",
payload: {
text: "Your reminder goes here!"
}.to_json
},
{
type: "sms",
minutes_before_event: …
```
=> [72430] Support Event Notifications

CHANGELOG.md, lib/nylas/api.rb, spec/nylas/api_spec.rb
The `exchange_code_for_token` method strips the response body from the server and returns just the `access_token`. Now, it allows the user to pass in a boolean to dictate whether or not to return the full server response. To preserve backwards compatibility, the default behaviour of the method will still return an `access_token`.
To return the entire full response body, pass in `return_full_response: true` with the `code`:
```ruby
response_body = api.exchange_code_for_token("code", return_full_response: true)
```
=> [69622] Allow `exchange_code_for_token` to return a full body

CHANGELOG.md, lib/nylas/account.rb, lib/nylas/calendar.rb, lib/nylas/draft.rb, lib/nylas/message.rb, lib/nylas/model.rb, spec/nylas/account_spec.rb, spec/nylas/message_spec.rb
The metadata feature first introduced for events has expended to `Calendar`, `Message` and `Account`. This PR adds support for this change. More information on the expansion of the metadata can be found here: https://developer.nylas.com/docs/developer-tools/api/metadata
```ruby
api.calendars.create(
name: "My New Calendar",
description: "Description of my new calendar",
location: "Location description",
timezone: "America/Los_Angeles",
metadata: {
event_type: "gathering"
}
)
calendar = api.calendars.last
calendar.update(metadata: {
test: "true",
}};
```
```ruby
calendars = api.calendars.where(metadata_pair: {event_type: "gathering"})
```
```ruby
message = api.messages.last
message.update(metadata: {
test: "true",
}};
```
```ruby
messages = api.messages.where({metadata_key: "test"});
``` …
=> [73525] Metadata Support for Calendars, Accounts, and Messages

.rubocop.yml, CHANGELOG.md, examples/plain-ruby/scheduler.rb, lib/nylas.rb, lib/nylas/api.rb, lib/nylas/scheduler_booking_confirmation.rb, lib/nylas/scheduler_booking_request.rb, lib/nylas/scheduler_collection.rb, lib/nylas/scheduler_time_slot.rb, spec/nylas/scheduler_collection_spec.rb
This PR adds the remaining Scheduler endpoints
```ruby
google_availability = nylas.scheduler.get_google_availability
o365_availability = nylas.scheduler.get_office_365_availability
```
```ruby
availabile_timeslots = nylas.scheduler.get_available_time_slots('slug')
```
```ruby
slot = Nylas::SchedulerTimeSlot.new(
account_id: "test-account-id",
calendar_id: "test-calendar-id",
emails: ["recipient@example.com"],
start: Time.at(1636728347),
end: Time.at(1636731958)
)
timeslot_to_book = Nylas::SchedulerBookingRequest.new(
additional_values: {
test: "yes"
},
email: "recipient@example.com",
locale: "en_US",
name: "Recipient Doe",
timezone: "America/New_York",
slot: slot
)
booking_confirmation = nylas.scheduler.book_time_slot("slug", timeslot_to_book)
```
```ruby
booking_confirmation = …
```
=> [73532] Support remaining Scheduler endpoints

CHANGELOG.md, examples/plain-ruby/drafts.rb, lib/nylas/draft.rb, lib/nylas/new_message.rb, spec/nylas/draft_spec.rb
This PR builds on #337, the API also supports adding metadata to a message either via adding to a Draft or sending directly through `/send`. Now both the `NewMessage` and `Draft` objects support metadata.
Add metadata to Draft:
```ruby
draft = api.drafts.create(to: [{ email: "not-a-real-email@example.com"}],
subject: "A new draft!",
metadata: {test: "yes"})
draft.send!
```
You can also add metadata directly to a new message being sent:
```ruby
message = api.send!(to: [{ email: "not-a-real-email@example.com"}],
subject: "A new message!",
metadata: {test: "yes"})
```
=> [75895] Enable metadata support for new Messages and Drafts

CHANGELOG.md, lib/nylas/model/attributable.rb, lib/nylas/model/attribute_definition.rb, lib/nylas/model/attributes.rb, lib/nylas/model/list_attribute_definition.rb, lib/nylas/participant.rb, lib/nylas/types.rb, lib/nylas/version.rb
A recent API update caused updating an event using the SDK to return an error because the SDK sends a Participant's status as well as an object key within the Event.when object. This PR also modifies how we serialize child objects for API calls, and ensure if we don't want to include read_only values that we enforce it throughout the child objects.
=> [75450] Fix bug where updating an Event results in an API error

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.6.1 release brings in the following fix/enhancement:
* Enabled support for adding metadata to a `NewMessage`/`Draft` (#341)
* Fix bug where updating an Event results in an API error (#340)
=> v5.6.1 Release

CHANGELOG.md, examples/plain-ruby/accounts.rb, lib/nylas.rb, lib/nylas/account.rb, lib/nylas/api.rb, lib/nylas/application_details.rb, lib/nylas/token_info.rb, spec/nylas/account_spec.rb, spec/nylas/api_spec.rb
This PR adds support for 3 Application-related endpoints. The Python SDK now is able to get and update application details as well as get information about an access token.
To get application details:
```ruby
app_id: APP_ID,
app_secret: APP_SECRET
)
app_data = nylas.application_details
```
To update application details:
```ruby
app_id: APP_ID,
app_secret: APP_SECRET
)
app_data = nylas.application_details
app_data.application_name = "New Name"
updated_app_data = nylas.updated_application_details(app_data)
```
To get information about an access token:
```ruby
app_id: APP_ID,
app_secret: APP_SECRET,
access_token: ACCESS_TOKEN
)
account = nylas.accounts.first
token_info = account.token_info("ACCESS_TOKEN")
```
I confirm …
=> [76795] Improved Application Detail support

CHANGELOG.md, gem_config.rb, lib/nylas/account.rb, lib/nylas/application_details.rb, lib/nylas/token_info.rb, spec/nylas/account_spec.rb
Enable the ability to delete an account via the `/a/{client_id}/accounts/{id}` [endpoint](https://developer.nylas.com/docs/api/#delete/a/client_id/accounts/id).
```ruby
app_id: APP_ID,
app_secret: APP_SECRET,
access_token: ACCESS_TOKEN
)
account = nylas.accounts.find('{id}')
account.destroy
```
=> [75855] Enable Account deletion

CHANGELOG.md, lib/nylas/folder.rb, spec/nylas/folder_spec.rb
The `Folder` class was sending over read-only attributes like `id`, `object`, and `account_id`. This PR fixes that, and adds test coverage for this.
=> [76799] Fix saving and deleting `Folder` objects

CHANGELOG.md, examples/plain-ruby/webhooks.rb, lib/nylas/webhook.rb, spec/nylas/webhook_spec.rb
The Nylas API supports creating, updating and deleting webhooks and this PR enables support for these additional operations. We also provide a couple of helper modules with strings representing various webhook `status` and `trigger`values.
We have provided some modules that can help with setting the correct values for webhooks:
```ruby
WebhookState::ACTIVE # = "active"
WebhookState::INACTIVE # = "inactive"
WebhookTrigger::ACCOUNT_CONNECTED # = "account.connected"
WebhookTrigger::MESSAGE_CREATED # = "message.created"
WebhookTrigger::THREAD_REPLIED # = "thread.replied"
WebhookTrigger::CALENDAR_UPDATED # = "calendar.updated"
```
To create a webhook:
```ruby
app_id: APP_ID,
app_secret: APP_SECRET,
access_token: ACCESS_TOKEN
)
webhook = nylas.webhooks.create( …
```
=> [76807] Improve webhook support

lib/nylas/calendar_collection.rb, spec/nylas/calendar_collection_spec.rb
This commit adds an optional keyword argument `calendar` to the
Nylas::CalendarCollection's availability related methods. This is
parameter is accepted by the latest API, but was not previously included
in the method definitions.
The argument requirements match the parameter requirements of the
endpoint. A user must provide one of `calendar` or `emails`
=> Support calendars keyword for availability requests

lib/nylas/calendar_collection.rb, spec/nylas/calendar_collection_spec.rb
This commit updates the keyword arguments for the interval parameter for
the availability-related methods to match the requirements of the API
endpoints.
According to the latest API, the availability endpoints expect an
`interval_minutes` rather than an `interval` keyword. Without this
change, the API throws an error:
```ruby
response = nylas_client.calendars.availability(
start_time: start_time.to_i,
end_time: end_time.to_i,
duration_minutes: duration_minutes,
interval: 30,
round_robin: "max-availability",
emails: [coach.email],
)
```
=> Update interval keyword arg for calendar availability methods

.rubocop.yml, CHANGELOG.md, lib/nylas/calendar_collection.rb, lib/nylas/version.rb, spec/nylas/calendar_collection_spec.rb
New `nylas` v5.8.0 release brings in the following features and enhancements:
* Improved support for `Webhook` objects (#349)
* Support `calendars` for availability methods (#350)
* Fix `interval_minutes` keyword for availability methods (#351)
=> v5.8.0 Release

CHANGELOG.md, lib/nylas/http_client.rb, pull_request_template.md, spec/nylas/http_client_spec.rb
This PR enables Nylas API v2.5 for the Ruby SDK
=> Enable Nylas API v2.5 support

CHANGELOG.md, lib/nylas/account.rb, spec/nylas/account_spec.rb
This PR adds a new field `authentication_type` in `Account` model
=> [TSDK-265] Add `authentication_type` field in `Account`

CHANGELOG.md, examples/plain-ruby/components.rb, lib/nylas.rb, lib/nylas/account.rb, lib/nylas/api.rb, lib/nylas/collection.rb, lib/nylas/component.rb, lib/nylas/http_client.rb, lib/nylas/model.rb, lib/nylas/webhook.rb, spec/nylas/account_spec.rb, spec/nylas/collection_spec.rb, spec/nylas/component_spec.rb, spec/nylas/deltas_collection_spec.rb, spec/nylas/draft_spec.rb, spec/nylas/event_spec.rb, spec/nylas/folder_spec.rb, spec/nylas/message_spec.rb, spec/nylas/model_spec.rb, spec/nylas/room_resource_spec.rb, spec/nylas/scheduler_spec.rb, spec/nylas/thread_spec.rb, spec/nylas/webhook_spec.rb, spec/spec_helper.rb
This PR enables basic auth support for the APIs that need it
=> [TSDK-281] Implement Basic Auth support

CHANGELOG.md, lib/nylas/new_message.rb
This PR adds an extra check when sending a `NewMessage` object by checking if the API response is a Hash before attempting to create a `Message` option out of it, preventing the chance of a `NoMethodError`. This PR closes issue #358.
=> Fix `NoMethodError` when calling `NewMessage#send!`

CHANGELOG.md, lib/nylas/participant.rb, spec/nylas/event_spec.rb
This PR adds the missing `phone_number` field in `Participant`.
=> Add missing `phone_number` field in `Participant`

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.9.1 release brings in the following features and changes:
* Add missing `phone_number` field in `Participant` (#360)
* Fix `NoMethodError` when calling `NewMessage#send!` (#359, #358)
=> v5.9.1 Release

examples/authentication/app.rb
https://www.google.com/m8/feeds/ is a deprecated scope. We have users relying on this example code for our authentication. This code won't work unless the scope mentioned is replaced with https://www.googleapis.com/auth/contacts
Related CC PR here (not public): https://github.com/nylas/cloud-core/pull/5960/files
=> Update app.rb to replace deprecated Google scopes

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.9.2 release brings in the following features and changes:
* Fix calendar availability not serializing `FreeBusy` and `OpenHours` properly (#364, #363)
* Fix Authentication demo app using deprecated Google scopes (#362)
=> v5.9.2 Release

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.10.0 release provides the following addition and fix:
* Support collective and group events (#366)
* Fix `ModelNotFilterableError` when querying for accounts with metadata (#367)
=> v5.10.0 Release

.rubocop.yml, CHANGELOG.md, lib/nylas/event.rb, lib/nylas/http_client.rb, spec/nylas/event_spec.rb
This PR adds support for event reminders.
```ruby
example_calendar = api.calendars.last
api.events.create(
title: "A fun event!",
location: "The Party Zone",
calendar_id: example_calendar.id,
when: { start_time: Time.now + 60, end_time: Time.now + 120 },
reminder_minutes: 20,
reminder_method: "email"
)
```
=> Add support for event reminders

CHANGELOG.md, lib/nylas/job_status.rb, spec/nylas/job_status_spec.rb
This PR adds a new `metadata` field to the `JobStatus` class.
=> Add `metadata` field to `JobStatus`

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.11.0 release provides the following addition and fix:
* Add support for event reminders (#370, #369)
* Add `metadata` field to `JobStatus` (#371)
=> v5.11.0 Release

lib/nylas/api.rb, spec/nylas/api_spec.rb
Hosted Authentication method was missing the provider and redirect_on_error params. I have added them and created a simple test
JIRA --> https://nylas.atlassian.net/browse/TSDK-366
=> TSDK-366 - Ruby SDK Hosted Authentication missing optional parameters

CHANGELOG.md, lib/nylas/calendar_collection.rb, spec/nylas/calendar_collection_spec.rb
This PR address the issue where, if `round_robin` is left as `nil`, it always yields an error. This is because the Nylas Docs were out of date for the availability endpoint. `round_robin` is optional, and when omitted, returns collective availability. However, sending `null` is not valid despite what it says in the documentation. Now, we omit the value from the json payload if the value is `nil`.
=> Fix calendar availability failing when `round_robin` is `nil`

CHANGELOG.md, lib/nylas/message.rb, spec/nylas/message_spec.rb
This PR adds a a new field for messages, `reply_to_message_id`
=> Add `reply_to_message_id` field in `Messages`

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.12.0 release brings the following:
* Add missing hosted authentication parameters #374 
* Add `reply_to_message_id` field in `Messages` #376 
* Fix calendar availability failing when `round_robin` is `nil` #375, #373 
=> v5.12.0 Release

lib/nylas/collection.rb
ruby 3 does not automatically expand keyword arguments
the create method in this class already does double-splat expansion
this change makes the new method match and fixes a ruby 3 regression
=> fix Collection new method to expand keyword args

CHANGELOG.md, lib/nylas/calendar.rb, lib/nylas/collection.rb, lib/nylas/draft.rb, lib/nylas/event.rb, lib/nylas/file.rb, lib/nylas/folder.rb, lib/nylas/label.rb, lib/nylas/message.rb, lib/nylas/model.rb, lib/nylas/thread.rb, spec/nylas/collection_spec.rb
This is built on #380, we enable the ability for getting the total count for every collection, regardless of their support on the API side.
=> Add support for getting `count` for collections not supported by the API

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.12.1 release brings the following:
* Add support for getting `ids` and `count` for collections not supported by the API (#380, #381, #378)
* Fix Ruby 3.x compatibility for expanding keyword arguments (#379)
=> v5.12.1 Release

.rubocop_todo.yml, CHANGELOG.md, gem_config.rb, gemfiles/Gemfile.rails5, lib/nylas/when.rb, spec/nylas/when_spec.rb
This PR adds the `timezone`, `start_timezone` and `end_timezone` fields. This SDK also now uses tzinfo as a dev dependency to validate the strings set by the user are indeed IANA database names.
=> Add timezone fields to the When class

CHANGELOG.md, lib/nylas/event.rb, spec/nylas/event_spec.rb
This PR adds the `visibility` attribute to the `Event` class.
=> Adds visibility attribute in Event.rb

CHANGELOG.md, lib/nylas/calendar.rb, spec/nylas/calendar_spec.rb
This PR adds support for the new colors field in the Calendar model. Please note that this field is read only, and for Microsoft calendars only.
=> Add support for calendar colors

.gitignore, CHANGELOG.md, lib/nylas/errors.rb, lib/nylas/http_client.rb, spec/nylas/http_client_spec.rb
This PR adds support for rate limit 429 headers from the API.
=> Add Rate Limit error support

lib/nylas/http_client.rb
Removes creating an instance of `StringIO` before passing the Nylas API response to the JSON parser.
Recently ran into into an issue when trying to fetch some bigger email messages. The requests were taking longer than expected but only when fetching via the Ruby SDK. A request via the Ruby SDK would take a couple of minutes to fetch these messages while a request directly via cURL for the same messages would only take a few seconds.
This change, as far as I can tell, implies no loss in functionality.
Some quick benchmark results of fetching one of the troublesome email messages before and after this change:
```ruby
Benchmark.measure { nylas.messages.find('...') }
```
```ruby
<Benchmark::Tms:0x000000010293a500
@cstime=0.0,
@cutime=0.0,
@label="",
@real=89.72193600004539,
@stime=0.454271, …
```
=> Skip creating instance of StringIO before parsing JSON

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.14.0 release brings the following:
* Added support for rate limit errors (#389)
* Added `disable_provider_selection` option for building auth URL (#395)
* Improved performance by skipping creating instance of StringIO before parsing JSON (#393)
=> v5.14.0 Release

.rubocop.yml, CHANGELOG.md, gem_config.rb, lib/nylas.rb, lib/nylas/services/tunnel.rb, spec/nylas/tunnel_spec.rb
This PR enables support for local webhook development. When implementing this feature in your app, the SDK will create a tunnel connection to a websocket server and registers it as a webhook callback to your Nylas account. 
During the setup process you can pass in methods to override the websocket client's callback methods. The most important method is the `on_message` method which returns a parsed delta event from the webhook server.
```ruby
app_id: CLIENT_ID,
app_secret: CLIENT_SECRET
)
def on_message(delta)
if delta.type == Nylas::WebhookTrigger::MESSAGE_UPDATED
p [:delta, delta]
end
end
config = {
"region": "us",
"triggers": [WebhookTrigger::MESSAGE_UPDATED],
"on_message": method(:on_message)
}
Nylas::Tunnel::open_webhook_tunnel(nylas, config)
```
I confirm …
=> Local webhook testing support

CHANGELOG.md, gem_config.rb, nylas.gemspec
This PR adds `tzinfo` as a runtime dependency as it is used by `Nylas::When`, as well as `faye-websockets` and `eventmachine` as used by `Nylas::Tunnel`.
=> Add `tzinfo` as a runtime dependency

CHANGELOG.md, lib/nylas/version.rb
New Nylas Ruby SDK v5.15.0 release brings the following additions:
* Add local webhook testing support (#399)
* Add `tzinfo`, `faye-websocket`, `eventmachine` as runtime dependencies (#401)
=> v5.15.0 Release

CHANGELOG.md, lib/nylas/webhook.rb
This PR fixes the `MESSAGE_LINK_CLICKED` value, and adds missing Job status webhook triggers.
=> Fix and add missing webhook triggers

lib/nylas/event.rb, spec/nylas/event_spec.rb
- Ruby SDK Event object was missing the fields `organizer_name` and `organizer_email`. The workaround previously was to parse the owner field of the Event object. 
https://nylas.atlassian.net/browse/CUST-1575
https://github.com/nylas/nylas-ruby/issues/406
=> Added attributes organizer_email and organizer_name to the Event Object

CHANGELOG.md, lib/nylas/event.rb, lib/nylas/version.rb, spec/nylas/event_spec.rb
New Nylas Ruby SDK v5.16.0 release brings the following additions:
* Add missing `provider_id` attribute to `Label` (#404)
* Add missing job status webhook triggers (#403)
* Fix `MESSAGE_LINK_CLICKED` trigger (#403)
=> v5.16.0 Release

CHANGELOG.md, lib/nylas/webhook.rb, spec/nylas/webhook_spec.rb
This PR adds support for verifying the webhook signature of inbound webhook notifications.
```ruby
require 'sinatra'
require 'nylas'
require 'json'
set :port, 9000
NYLAS_CLIENT_SECRET = ENV['NYLAS_CLIENT_SECRET']
post '/' do
content_type :json
x_nylas_signature = request.env['HTTP_X_NYLAS_SIGNATURE']
raw_body = request.body.read
unless Nylas::Webhook::verify_webhook_signature(NYLAS_CLIENT_SECRET, x_nylas_signature, raw_body)
status 403
return { error: 'Invalid signature' }.to_json
end
body = JSON.parse(raw_body)
puts "Webhook event received: #{JSON.pretty_generate(body)}"
status 200
{ success: true }.to_json
end
run Sinatra::Application.run!
```
I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on …
=> Add support for verifying webhook signatures

lib/nylas/api.rb, lib/nylas/native_authentication.rb, spec/nylas/native_authentication_spec.rb
Adds a `return_full_response` argument to the `Api#authenticate` method, along with it an implementation in `NativeAuthentication` which mirrors the code in the `exchange_code_for_token` method.
This let's us perform NativeAuthentication, and get back the full token response vs just the access token. On the implementers end, this lets us share some of our account creation code between the two different types of authentication by being able to rely on the full_response.
Why is this needed? Nylas webhooks come in as "skinny payloads", just enough information to make a request to get the objects data with a request back to Nylas's servers (see: https://developer.nylas.com/docs/developer-guide/webhooks/available-webhooks/#event-webhooks). A calendar event's may look something like:
``` …
```
=> Allow native authentication to return the  full response like the exchange_code_for_token

lib/nylas/event.rb, spec/nylas/event_spec.rb
The API returns `updated_at` for events, but it is not included in the ruby client event model. This PR adds the `updated_at` attribute and related spec. This was referenced in #407 which was closed by #409, but it didn't actually add the `updated_at` attribute.
=> Added event.updated_at

CHANGELOG.md, lib/nylas/version.rb
New Nylas Ruby SDK v5.17.0 release brings the following additions:
* Added support for verifying webhook signatures (#413)
* Added `event.updated_at` (#410)
* Allow native authentication to return the full response like the `exchange_code_for_token` (#411)
=> v5.17.0 Release

README.md, gem_config.rb, lib/nylas.rb, lib/nylas/client.rb, lib/nylas/handler/http_client.rb, lib/nylas/resources/auth.rb, lib/nylas/resources/messages.rb, lib/nylas/resources/resource.rb
CRUD support for Messages API (Ruby)
https://nylas.atlassian.net/browse/AV-2686
=> Add support for read, update, and delete for messages

CHANGELOG.md, lib/nylas/handler/http_client.rb, lib/nylas/resources/smart_compose.rb, lib/nylas/resources/webhooks.rb, lib/nylas/version.rb
* Added additional error classes (#426)
* Added support for free/busy endpoint (#428)
* Added support for Messages, Drafts, and Smart Compose APIs (#432)
* Added support for custom authentication, connectors, and credentials APIs (#431)
* Added support for folders API (#433)
* Added support for attachments API (#434)
* Set default timeout to 30 seconds (#426)
=> v6.0.0 beta 2 release

CHANGELOG.md, lib/nylas/utils/file_utils.rb
This PR fixes a bug that arises when sending messages and creating or modifying drafts without any attachments present.
=> Fixed issue when sending message without attachments

CHANGELOG.md, lib/nylas/api.rb, spec/nylas/api_spec.rb
This PR adds support for the /connect/detect-provider endpoint. Closes #421.
=> Add support for detect provider endpoint

lib/nylas/resources/drafts.rb
The Drafts endpoint on the Ruby SDK doesn’t have a Send option. This PR will add it.
https://nylas.atlassian.net/browse/TW-2456
=> Tw 2456 ruby add send to drafts

.github/workflows/rubocop.yml, CHANGELOG.md, lib/nylas/api.rb, lib/nylas/search_collection.rb, lib/nylas/types.rb, spec/nylas/search_collection_spec.rb
This PR adds count support for SearchCollection type. Closes #416.
=> Add support for count on message/thread search

lib/nylas/http_client.rb
We set a content-header type by default, but not an accept header. We should add it in to prevent some error messages not being formatted as JSON. Closes #405.
=> Add accept header by default

CHANGELOG.md, lib/nylas/contact.rb, spec/nylas/contact_spec.rb, spec/spec_helper.rb
This PR ensured that when we are dealing with contact picture, that we are using the correct encoding. Closes #422.
=> Fix contact picture encoding error

lib/nylas/resources/events.rb
- Added send-rsvp support for events api
[JIRA](https://nylas.atlassian.net/browse/AV-2762)
=> Added send-rsvp support for events api

CHANGELOG.md, lib/nylas/client.rb, lib/nylas/resources/auth.rb, lib/nylas/resources/grants.rb
⚠️ This is a breaking change ⚠️ 
This PR moves the following:
* `Auth.grants()` to `NylasClient.grants()`
* `Grants.create()` to `Auth.customAuthentication()`
Functionality remains the same.
=> Move `Grants` to `NylasClient` and custom authentication to `Auth`

CHANGELOG.md, lib/nylas/resources/drafts.rb, lib/nylas/resources/events.rb, lib/nylas/version.rb
* **BREAKING CHANGE**: Moved grants API out of `Auth` to `NylasClient` (#447)
* **BREAKING CHANGE**: Moved `Grants.create()` to `Auth.customAuthentication()` (#447)
* Add support for contacts API (#438)
* Add support for send RSVP (#444)
* Add draft send support (#446)
* Add missing webhook triggers (#445)
* Fixed issue when sending message without attachments (#437)
* Fixed issue when building an OAuth2 URL (#449)
* Fixed free-busy endpoint path (#440)
=> v6.0.0 beta 3 Release

CHANGELOG.md, lib/nylas/resources/auth.rb
This PR fixes the PKCE code challenge generation; the correct method the API wants is for us to base64 encode the hex string as opposed to base64 encoding resulting hashed bytearray directly.
=> Fix incorrect PKCE code challenge generation

CHANGELOG.md, lib/nylas/resources/auth.rb
We were encoding our URL prematurely, causing an error to be thrown when setting additional parameters (PKCE, etc.)
=> Fixed incompatible types when building OAuth2 URL

lib/nylas/draft.rb, spec/nylas/draft_spec.rb
Support filtering draft messages, using the `/drafts` endpoint according to the [documentation](https://developer.nylas.com/docs/api/v2/#get-/drafts). 
As an example, this allows querying for drafts on a given a `thread_id` using:
```
nylas_api.drafts.where(thread_id:)
```
=> support draft filtering

lib/nylas/resources/auth.rb
Fix url_auth_builder call
This line:
```
builder.query = URI.encode_www_form(build_query(config)).gsub!("+", "%20")
```
Replaces the whole value, so the Auth doesn’t work.
Replaced it with this:
```
builder.query = URI.encode_www_form(build_query(config)).gsub(/\+/, "%20")
```
https://nylas.atlassian.net/browse/TW-2543
=> Fix OAuth URL building

CHANGELOG.md, lib/nylas/version.rb
* Fixed a bug during OAuth URL building (#462)
* Fixed a bug where the `next_cursor` field was omitted for list responses (#461)
=> v6.0.1 Release

lib/nylas/resources/webhooks.rb, spec/nylas/resources/webhooks_spec.rb
Changed Action and URL path
https://nylas.atlassian.net/browse/TW-2579
=> Update Webhook's Rotate Secret

CHANGELOG.md, lib/nylas/client.rb, spec/nylas/client_spec.rb
The API's default timeout is 90 seconds, so it's best we match that. We have updated the default value to match this, user can still override the default.
=> Change default timeout to match API (90 seconds)

CHANGELOG.md, lib/nylas/resources/drafts.rb, lib/nylas/resources/messages.rb, lib/nylas/utils/file_utils.rb, spec/nylas/resources/drafts_spec.rb, spec/nylas/resources/messages_spec.rb
This PR improves message send/draft create/update performance by always defaulting to application/json instead of multipart. Multipart will only be used for when a request contains a total attachments size of 3mb or higher.
=> Improved message sending and draft create/update performance

CHANGELOG.md, lib/nylas/version.rb
* Improved message sending and draft create/update performance (#470)
* Change default timeout to match API (90 seconds) (#471)
* Fixed error when invoking `Auth.detect_provider` (#469, #468)
=> v6.0.3 Release

lib/nylas/resources/messages.rb, spec/nylas/resources/messages_spec.rb
Adding support for query_params to retrieve headers for messages along with field selection. `select` API parameter. It is addressing CUST-2909
=> Adding support for query_params for messages endpoint

CHANGELOG.md, lib/nylas/resources/drafts.rb, lib/nylas/resources/messages.rb, lib/nylas/utils/file_utils.rb, spec/nylas/resources/drafts_spec.rb, spec/nylas/resources/messages_spec.rb, spec/nylas/utils/file_utils_spec.rb
We were not encoding the attachments properly for attachments less than 3MB. They should be b64 encoded. Now it should handle it correctly.
=> Fix sending attachments less than 3MB

Gemfile, nylas.gemspec
Hi there,
In my current organisation, we are trying to upgrade to nylas API v3, however nylas 6.x Ruby SDK conflicts with one of our [chargebee-ruby ](https://github.com/chargebee/chargebee-ruby) sub-dependency:
```
chargebee (2.43.0)
rest-client (>= 1.8, <= 2.0.2)
nylas (6.1.1)
rest-client (~> 2.1, < 3.0) 
```
While there's already a PR to upgrade chargebee usage of rest-client, https://github.com/chargebee/chargebee-ruby/pull/83, we're unsure whether that will land on time, so we were wondering whether for the time being we could loosen up the version on your side?
When running the CI against `rest-client 2.0.0` there seems to be ✅. Do you see any repercussions against doing that?
```
❯ bi
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using …
```
=> Loosen rest-client version

CHANGELOG.md, lib/nylas/utils/file_utils.rb, spec/nylas/utils/file_utils_spec.rb
This PR enables the SDK to re-attach large files when trying to retry the same request body. If a `file_path` is provided with the attachment request and the file stream is closed, the SDK will attempt to reopen it. The helper function `attach_file_request_builder` will now set the `file_path` in the object, so if you're currently using that helper function, the attachment will be ready for reattachment. 
=> Enable SDK to reattach large files to messages on retry

CHANGELOG.md, nylas.gemspec
As reported by @bmulholland:
```
warning: lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Also please contact the author of nylas-6.1.1 to request adding ostruct into its gemspec.
```
Closes #489.
=> Add dependency on ostruct gem

CHANGELOG.md, lib/nylas/resources/folders.rb, spec/nylas/resources/folders_spec.rb
This PR adds the ability to pass query parameters for listing folders. Closes #488.
=> Added query support for folders

CHANGELOG.md, lib/nylas/version.rb
* Added query support for folders (#492, #488)
* Added dependency on `ostruct` gem (#491, #489)
* Enable SDK to reattach large files to messages on retry (#487)
* Downgraded `rest-client` to `2.0` for better compatibility (#490)
=> v6.2.0 Release

CHANGELOG.md, lib/nylas/handler/http_client.rb, spec/nylas/handler/http_client_spec.rb
- Added`Accept-Encoding: gzip` header to HTTP requests.
-  This change allows the client to request Gzip-compressed responses from the server, improving data transfer efficiency and reducing load times.
=> Adding support for `Accept-Encoding: gzip` in HTTP headers

CHANGELOG.md, lib/nylas/handler/http_client.rb, spec/nylas/handler/http_client_spec.rb
=> Revert "Adding support for `Accept-Encoding: gzip` in HTTP headers"

CHANGELOG.md, lib/nylas/resources/folders.rb, lib/nylas/resources/threads.rb, spec/nylas/resources/folders_spec.rb, spec/nylas/resources/threads_spec.rb
- Add `select` field to `GET folders/id` 
- https://github.com/nylas/nylas-ruby/issues/499
=> Add select field to folders find method

lib/nylas/utils/file_utils.rb, spec/nylas/utils/file_utils_spec.rb
When adding an attachment to an email, the filename that will be sent is determined by the provided file path. This is problematic when using `Tempfile` because part of the path will be random. I propose accepting an optional `filename` parameter in `FileUtils.attach_file_request_builder`.
=> Allow custom filename when adding an attachment

lib/nylas/utils/file_utils.rb, spec/nylas/utils/file_utils_spec.rb
Add support for attachments > 3MB.
Follow-up of #496.
=> Support custom attachment filename for large files

CHANGELOG.md, lib/nylas/resources/bookings.rb, spec/nylas/resources/bookings_spec.rb
- Added booking support for Scheduler private configuration.
=> Add booking support for Scheduler private configurations

lib/nylas/errors.rb
Adjusted the gendoc to show that the `provider_error` is a Hash, not a String. Per customer message.
=> Adjust gendoc to correctly show this as a hash

lib/nylas/utils/file_utils.rb, spec/nylas/utils/file_utils_spec.rb
- Add ability to provide `content_id` so developers can send inline image using cid in the body.
- https://github.com/nylas/nylas-ruby/issues/505
=> Add ability to send inline image > 3mb

CHANGELOG.md, lib/nylas/version.rb
* Added support for private Scheduling configuration (#503).
* Added ability to add optional `content_id` to support inline image on `send` (#506) (#505).
* Added custom filename support for large attachments (#502).
* Adjusted the gendoc to show that the `provider_error` is a Hash (#504).
=> v6.2.2 Release

CHANGELOG.md, lib/nylas/handler/http_client.rb, nylas.gemspec, spec/nylas/handler/http_client_spec.rb
Due to unexpected errors such as Bad Gateway, the response object is of Instance string, while trying to fetch the provider_error we return a Ruby error of 
`undefined method `fetch' for "Bad Gateway":String`
This PR addresses the type before parsing the provider_error property
=> Handle response objects of instance String for API errors

lib/nylas/handler/api_operations.rb, lib/nylas/handler/http_client.rb, spec/nylas/handler/api_operations_spec.rb, spec/nylas/handler/http_client_spec.rb
Adding response headers to the response Hash
=> Adding response headers to Ruby SDK

CHANGELOG.md, lib/nylas/utils/file_utils.rb, spec/nylas/utils/file_utils_spec.rb
Remove file_path from the attachments object to prevent invalid requests in the future via our Send API.
=> Remove file_path from build JSON request

CHANGELOG.md, lib/nylas/version.rb
* Removed `file_path` from `File` object to match the Send API schema
* Added events import function to the RubySDK
* Added response headers to Ruby SDK 
=> Release v6.3.0

lib/nylas/handler/http_client.rb, spec/nylas/handler/http_client_spec.rb
There should be no reason for the API to respond with a `200 OK` and an empty body, however, sometimes that has happened to us, resulting in this exception:
```
NoMethodError: undefined method `[]' for nil
```
This comes from:
* `nylas/handler/api_operations.rb` in `get_list` at line `34`
* `nylas/resources/messages.rb` in `list` at line `31`
Instead of raising a `NoMethodError` when trying to access `response`, `parse_response` now explicitly checks that it's returning *something*.
=> raise an explicit exception when response does not include a JSON body

CHANGELOG.md, lib/nylas/version.rb
=> Release v6.4.0

.gitignore, CHANGELOG.md, examples/messages/file_upload_example.rb, examples/messages/send_attachments.rb, lib/nylas/handler/http_client.rb, lib/nylas/resources/messages.rb, spec/nylas/handler/http_client_spec.rb, spec/nylas/utils/file_utils_spec.rb
Reported in issue #528 - see a similar issue reported here https://github.com/jnunemaker/httparty/issues/671
Fixes: Encoding::CompatibilityError when sending multipart requests with UTF-8 content
Closes: #528
https://nylas.atlassian.net/browse/TW-3983
=> Added support for string-content attachments & fixed HTTParty encoding issues.

CHANGELOG.md, lib/nylas/version.rb
* Added support for `single_level` query parameter in Folders API for Microsoft accounts
* Added support for `include_hidden_folders` query parameter in folders list endpoint for Microsoft accounts to control whether hidden folders are included in the response
* Added support for passing in string contents for multipart and base64 (<3MB) attachments (#528) 
* Fixed HTTParty encoding compatibility issue with multipart requests (#528)
=> Release v6.6.0
