nylas/nylas-ruby

lib/draft.rb
To be used as documented in: https://www.nylas.com/docs/api#sending
=> Add reply_to_message_id parameter to Draft

Gemfile, inbox.gemspec, nylas.gemspec
Fixing this issue: http://stackoverflow.com/questions/31661394/how-to-solve-gem-compatibly-issues-in-bundler
=> Relax rest-client version requirement for better compatibility

lib/file.rb
https://github.com/nylas/nylas-ruby/issues/34
=> Add content_id parameter

lib/restful_model_collection.rb, spec/fixtures/threads_reply.txt, spec/restful_model_collection_spec.rb
=> Return an external Enumerator when no block given

README.md, lib/message.rb, spec/draft_spec.rb, spec/fixtures/draft_save.txt, spec/fixtures/send_endpoint.txt
=> Add reply_to field to Message class

Gemfile, LICENSE.txt, lib/draft.rb, lib/file.rb, lib/inbox.rb, lib/message.rb, lib/restful_model.rb, spec/draft_spec.rb, spec/file_spec.rb, spec/inbox_spec.rb, spec/message_spec.rb, spec/restful_model_collection_spec.rb
=> Fix sending issues

lib/draft.rb, spec/draft_spec.rb
This feature has been missing from the SDK and has been added by various forks. This PR updates the test, so should be safe to merge.
=> Add tracking param to Drafts

README.md
Correct markdown formatting for "Requirements" section.
=> Update formatting of README.md

lib/account.rb, lib/api_account.rb, lib/nylas.rb
Resolves https://github.com/nylas/nylas-ruby/issues/115
=> Add missing fields to Account model

lib/nylas.rb, lib/thread.rb
Resolves https://github.com/nylas/nylas-ruby/issues/116
=> Add missing fields (version, last_message_sent, last_message_received) to threads

gemfiles/Gemfile.rails4.lock, gemfiles/Gemfile.rails5.lock, gemfiles/Gemfile.rest-client.1.lock, gemfiles/Gemfile.rest-client.2.lock, lib/nylas.rb, lib/nylas/api/delta_stream.rb, nylas.gemspec
`Nylas::API#delta_stream` is not always needed but it requires to install several gems.
This is an attempt to fix this.
=> Don't require em-http and yajl if streaming is not needed.

README.md
This updates the documentation on the 3.X branch so that people coming to it are in a good place.
=> Point the 3.X documentation to the correct locations

lib/nylas.rb, lib/nylas/restful_model.rb
I wanted to force-push but #149 has already been merged :)
Ref #149
=> Minor syntactical cleanup to migrate to modern ruby hash syntax.

README.md, lib/nylas/restful_model_collection.rb, spec/restful_model_collection_spec.rb
Resolves https://github.com/nylas/nylas-ruby/issues/126
=> Add support for thread and message search

README.md, lib/nylas/event.rb, lib/nylas/message.rb, lib/nylas/restful_model_collection.rb, spec/message_spec.rb
Resolves https://github.com/nylas/nylas-ruby/issues/119
=> Message and Draft objects expose their related events

examples/plain-ruby/messages.rb, examples/plain-ruby/threads.rb, lib/nylas.rb, lib/nylas/api.rb, lib/nylas/collection.rb, lib/nylas/constraints.rb, lib/nylas/email_address.rb, lib/nylas/event.rb, lib/nylas/file.rb, lib/nylas/folder.rb, lib/nylas/message.rb, lib/nylas/message_headers.rb, lib/nylas/model.rb, lib/nylas/participant.rb, lib/nylas/timespan.rb, lib/nylas/types.rb, spec/nylas/collection_spec.rb, spec/nylas/message_spec.rb
Have some work to do with search and filtering still, but the entire message can be deserialized, including it's Event, File, Folder, and Labels objects.
=> Support Messages CRUD

examples/listening-for-webhooks/Gemfile, examples/listening-for-webhooks/README.md, examples/listening-for-webhooks/demo-app.rb, examples/plain-ruby/webhooks.rb, lib/nylas.rb, lib/nylas/api.rb, lib/nylas/delta.rb, lib/nylas/delta/object_data.rb, lib/nylas/deltas.rb, lib/nylas/email_address.rb, lib/nylas/event.rb, lib/nylas/file.rb, lib/nylas/folder.rb, lib/nylas/im_address.rb, lib/nylas/label.rb, lib/nylas/message.rb, lib/nylas/message_headers.rb, lib/nylas/model/attributes.rb, lib/nylas/nylas_date.rb, lib/nylas/participant.rb, lib/nylas/phone_number.rb, lib/nylas/physical_address.rb, lib/nylas/timespan.rb, lib/nylas/types.rb, lib/nylas/web_page.rb, lib/nylas/webhook.rb, spec/nylas/deltas_spec.rb
@khamidou - You'll probably want to look at both the webhook example sinatra application, as well as the webhook examples for listing the registered webhooks.
=> Deltas sent via webhook  are parsed into ruby objects

lib/nylas/http_client.rb, spec/nylas/api_spec.rb
Python SDK: https://github.com/nylas/nylas-python/pull/112
Node SDK: https://github.com/nylas/nylas-nodejs/pull/106
=> Add X-Nylas-Client-Id header

lib/nylas/account.rb, spec/nylas/account_spec.rb
Implement revoke-all api method from Account Management spec:
https://docs.nylas.com/reference#revoke-all
=> add account revoke-all method

.travis.yml
https://docs.travis-ci.com/user/languages/ruby/#bundler-20
=> Bundler 1.3 for Rails 4 on Travis CI

CHANGELOG.md, lib/nylas/model.rb
https://www.rubocop.org/en/latest/cops_lint/#linttojson
=> Add optional argument for #to_json

CHANGELOG.md, lib/nylas/version.rb
version bump for ip_addresses endpoint
=> release and version

CHANGELOG.md, lib/nylas/version.rb
=> Revert "release and version"

lib/nylas/contact.rb, spec/nylas/contact_spec.rb
customer that is using our ruby sdk has requested this change
=> adding source attribute to contact model

lib/nylas/file.rb, lib/nylas/model/attributable.rb, lib/nylas/model/transferable.rb, spec/nylas/thread_spec.rb
Right now build is failing on travis for the rubocop.
This PR aims to make travis pass and fix the rubocop related changes.
=> Rubocop fixes

Contributing.md, README.md, pull_request_template.md
This PR reorganizes the content of the Readme to direct Nylas users to content in the Nylas docs. It also adds a new Contributing and pull_request_template file.
=> Readme improvements and new Contributing and PR template files.

spec/nylas/event_spec.rb
This PR adds basic spec for `Nylas::Event` class as these were
missing and also requested in #244
=> Add spec for `Nylas::Event`

.github/workflows/rspec.yml, gem_config.rb, lib/nylas/collection.rb, lib/nylas/deltas_collection.rb, lib/nylas/message.rb, lib/nylas/model.rb, lib/nylas/thread.rb, spec/nylas/deltas_spec.rb
=> Fixes for Ruby 3

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.6.0 release bringing in the following new features:
* Add support for event notifications (#335)
* Add more Scheduler support (#338)
* Add metadata support for `Calendar`, `Message` and `Account` (#337)
* Modify `exchange_code_for_token` to allow returning a full body (#336)
=> v5.6.0 Release

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.7.0 release brings in the following features and enhancements:
* Add job status support (#342)
* Add `Event` to ICS support (#346)
* Add support for getting access token information (#345)
* Improved support for Application Details (#345)
* Enable ability to delete `Account` objects (#344)
* Fix saving and deleting `Folder` objects (#347)
=> v5.7.0 Release

CHANGELOG.md, lib/nylas.rb, lib/nylas/calendar_collection.rb, lib/nylas/event.rb, lib/nylas/time_slot.rb, lib/nylas/time_slot_capacity.rb, spec/nylas/calendar_collection_spec.rb, spec/nylas/event_spec.rb, spec/nylas/free_busy_collection_spec.rb
This PR bring support to [collective](https://developer.nylas.com/docs/connectivity/calendar/calendar-availability/#collective-meetings) and [group events](https://developer.nylas.com/docs/connectivity/calendar/calendar-availability/#group-meetings).
=> [TSDK-297] Support collective and group events

.github/workflows/rspec.yml, README.md, gem_config.rb, spec/spec_helper.rb
This PR adds codecov support to the repo and adds the code coverage statistic shield on the readme.
=> Add codecov support

CHANGELOG.md, lib/nylas/version.rb
New `nylas` v5.13.0 release brings the following:
* Add timezone fields to the `When` class (#384)
* Adds visibility attribute to `Event` class (#385)
* Add support for calendar colors (for Microsoft calendars) (#386)
=> v5.13.0 Release

lib/nylas.rb, lib/nylas/handler/api_operations.rb, lib/nylas/handler/http_client.rb, lib/nylas/resources/base_resource.rb, lib/nylas/resources/calendars.rb
=> Skeleton cleanup

.github/workflows/sdk-reference.yaml
=> Added github action to generate SDK references

.github/workflows/rubocop.yml, CHANGELOG.md, README.md, lib/nylas/client.rb, lib/nylas/handler/admin_api_operations.rb, lib/nylas/handler/api_operations.rb, lib/nylas/handler/grants_api_operations.rb, lib/nylas/handler/http_client.rb, lib/nylas/resources/applications.rb, lib/nylas/resources/auth.rb, lib/nylas/resources/calendars.rb, lib/nylas/resources/resource.rb, lib/nylas/version.rb
This PR is for releasing the first beta of v6 on RubyGems.
=> v6.0.0.beta.1 Release

CHANGELOG.md, README.md, UPGRADE.md, lib/nylas/client.rb, lib/nylas/errors.rb, lib/nylas/handler/http_client.rb
This PR adds an upgrade doc, updates the readme, adds more error classes and a default timeout.
=> Add better documentation, more errors, default timeout

CHANGELOG.md, lib/nylas/resources/calendars.rb
This PR adds support for the free busy endpoint.
=> Add Free-Busy Support

lib/nylas.rb, lib/nylas/client.rb, lib/nylas/handler/http_client.rb, lib/nylas/resources/attachments.rb
This PR adds support for the Attachments API
=> Ruby Attachments API support

lib/nylas/resources/webhooks.rb
Added webhook triggers for:
* Message Opened
* Message Link Clicked
* Thread Replied
https://nylas.atlassian.net/browse/TW-2455
=> Add missing webhook triggers

CHANGELOG.md, lib/nylas/resources/auth.rb
There is a syntax error when calling `build_query`.
=> Fix OAuth URL building throwing an error

lib/nylas/resources/contacts.rb
To match the other SDKs in consistency. 
=> Update contact_groups to list_groups

CHANGELOG.md, lib/nylas/version.rb
* **BREAKING CHANGE**: Renamed `Applications.info()` to `Applications.get_details()` for consistency
* **BREAKING CHANGE**: Changed return type of `Auth.url_for_oauth2_pkce()` from `OpenStruct` to a hash for consistency
* Added support for detecting providers
* Added enhanced support for the `Webhooks` API
* Default `client_secret` to the configured `api_key` for token exchange methods if not provided
* Fixed list and find scheduled messages
* Fixed incorrect PKCE code challenge generation
* Fixed incompatible types when building OAuth2 URL
* Fixed construction of query parameters
* Fixed construction of OAuth2 URL
* Fixed typo in paths for `Grants` class
I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this …
=> v6.0.0 beta 4 release

lib/nylas/resources/grants.rb, spec/nylas/resources/grants_spec.rb
Add Patch operation, as it is needed when doing Update Grant
https://nylas.atlassian.net/browse/TW-2578
=> Update Grants.rb add Patch

CHANGELOG.md, lib/nylas/version.rb
* Fixed the HTTP operation of updating grants (#464)
* Fixed endpoint URL of rotating webhooks (#465)
=> v6.0.2 Release

lib/nylas/resources/webhooks.rb
Add Folder.Created, Folder.Updated, Folder.Deleted
=> Ruby SDK - Add Folder Triggers

lib/nylas/resources/messages.rb
Added Clean Conversations to the Ruby SDK
https://nylas.atlassian.net/browse/TW-3015
=> Upate message.rb to add clean conversations

lib/nylas/resources/auth.rb
Add accessTokenInfo method
Add missing accessTokenInfo method
https://nylas.atlassian.net/browse/TW-2883
=> Update auth.rb add accessTokenInfo

lib/nylas/resources/webhooks.rb
Added message.created and message.updated
https://nylas.atlassian.net/browse/TW-2781
=> Ruby SDK - Add missing Webhook triggers

CHANGELOG.md, lib/nylas/version.rb
* Added query support for messages (#480)
* Added support for clean messages (#476)
* Added support for getting access token info (#475)
* Added new webhook triggers (#473, #479)
=> v6.1.0 Release

CHANGELOG.md, lib/nylas/handler/http_client.rb, spec/nylas/handler/http_client_spec.rb, spec/spec_helper.rb
=> Including headers in response #2 (fix tests/CI)
